apiVersion: install.istio.io/v1alpha1
kind: IstioOperator

spec:

  meshConfig:

    enableTracing: true

    defaultConfig:
      tracing: {}

    extensionProviders:

      - name: jaeger

        opentelemetry:

          port: 4317

          service: jaeger-collector.istio-system.svc.cluster.local
