name: Learn GitHub Actions

on:
  push:
    branches:
      - main

jobs:

  learn-runner:

    runs-on: ubuntu-latest

    steps:

      - name: Download repository to runner
        uses: actions/checkout@v6

      - name: Show where I am
        run: pwd

      - name: Show repository files
        run: ls -la

      - name: Show operating system
        run: uname -a

      - name: Print message
        run: echo "This command is running on a GitHub Actions runner"
